language: python
python:
 - "2.7"

notifications:
    email: false

install:
    - pip install -r src/fabric_bolt/requirements/local.txt --use-mirrors

script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)+src
    - python src/fabric_bolt/manage.py syncdb --settings=fabric_bolt.core.settings.test
    - python src/fabric_bolt/manage.py migrate --settings=fabric_bolt.core.settings.test
    - python src/fabric_bolt/manage.py test projects hosts accounts --settings=fabric_bolt.core.settings.test
